version: "3.9"

services:
  db:
    image: postgres:16   # pin to a stable major version
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase

    ports:
      - "5432:5432"

    volumes:
      - dbVol:/var/lib/postgresql/data

    command: ["postgres", "-c", "logging_collector=on"]

volumes:
  dbVol:
    driver: local
    driver_opts:
      type: none
      device: "C:\\Docker\\db1"
      o: bind
